Repository webuko/backend, pull requests merged in 2021-05, with the labels that each got.

#18 #17: (In place of slvnwhrl) Created initial model for price prediction
  model/airbnb_price_net/saved_model.pb
  model/airbnb_price_net/variables/variables.data-00000-of-00001
  model/airbnb_price_net/variables/variables.index
  model/price_predictor.ipynb
Labels: model

#30 Updated publish workflows and Dockerfiles
  .github/workflows/api-publish.yaml
  .github/workflows/snapshot-publish.yaml
  api/Dockerfile.flask
  api/code/app.py
  api/requirements.txt
  db/Dockerfile.db
  dc-production.yaml
  docker-compose.yaml
Labels: CI, backend

#32 Feature/api calls
  .github/workflows/snapshot-publish.yaml
  api/code/app.py
  api/code/flaskr/model.py
  api/code/flaskr/request_helper.py
  api/requirements.txt
  api/tests/test_model.py
Labels: backend, frontend

#35 #23: changed values for binary parameters (boolean instead of integers)
  api/code/flaskr/model.py
  api/tests/test_model.py
Labels: backend

#37 New API Method: Average price per neighbourhood
  README.md
  api/code/flaskr/model.py
  api/code/flaskr/request_helper.py
  api/code/flaskr/routes.py
  api/tests/test_model.py
  api/tests/test_request_helper.py
Labels: User Story, backend

#39 Documentation including Swagger API docs
  api/code/flaskr/__init__.py
  api/code/flaskr/db.py
  api/code/flaskr/model.py
  api/code/flaskr/request_helper.py
  api/code/flaskr/routes.py
  api/code/flaskr/swagger.yaml
  api/tests/test_model.py
Labels: backend, documentation
